TEAM_INFO_KEYS = {
    "TEAM-NAME": "Name",
    "TEAM-CITY": "City",
    "TEAM-AST": "Number of team assists",
    "TEAM-FG3_PCT": "Percentage of 3 points",
    "TEAM-FG_PCT": "Percentage of field goals",
    "TEAM-LOSSES": "Losses",
    "TEAM-PTS": "Total points",
    "TEAM-PTS_QTR1": "Points in 1st quarter",
    "TEAM-PTS_QTR2": "Points in 2nd quarter",
    "TEAM-PTS_QTR3": "Points in 3rd quarter",
    "TEAM-PTS_QTR4": "Points in 4th quarter",
    "TEAM-REB": "Rebounds",
    "TEAM-TOV": "Turnovers",
    "TEAM-WINS": "Wins",
}

PLAYER_INFO_KEYS = {
    "PLAYER_NAME": "",  # "Name",
    "TEAM_CITY": "Team city",
    "AST": "Assists",
    "BLK": "Blocks",
    "DREB": "Defensive rebounds",
    "FG3A": "3-pointers attempted",
    "FG3M": "3-pointers made",
    "FG3_PCT": "3-pointer percentage",
    "FGA": "Field goals attempted",
    "FGM": "Field goals made",
    "FG_PCT": "Field goal percentage",
    "FTA": "Free throws attempted",
    "FTM": "Free throws made",
    "FT_PCT": "Free throw percentage",
    "MIN": "Minutes played",
    "OREB": "Offensive rebounds",
    "PF": "Personal fouls",
    "PTS": "Points",
    "REB": "Total rebounds",
    "START_POSITION": "Position",
    "STL": "Steals",
    "TO": "Turnovers",
}
